language: android
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_058df639d3fc_key -iv $encrypted_058df639d3fc_iv -in datakit/release-key.keystore.enc -out datakit/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: cIm0wHJyBBd8CB1k1S/fT+Bao+zOD7YkWETaoVK7Bl3g3qPXXtSvHTiqoP6oEAgT2MeR+ND4MvlooC7WcahjZs9FgRiezmhotCN8iW6rZUroirXiFDxC+0J8TyTmBBNUDovbGQZXtEbfMApAQZA2BBBCat15G+7o40jO7sNjRG8eBMbbmKj8jeytSLKP4J01SYEJYOIgz/cibddweF6ZKOgNWgQp6hOmaxMMUPSzzF916YSCkiHFkohMMt6YNAPfP7kTrhqIzZzHN+bftWToIgMwlTjovW+NwArVJJF3k10NCw1HN3H/hnZhsBU5+uifV5lUhFagd7Bbp23nFO45qvHUE1jzp+08S+Z6OhfIAJyivudiDLm/aU46345NfoBvGkYE8hFm/EIe8AD1Ft8X7yZWXwDwhLDrAAqo9EVKgz86N1I72aiTcXPkPtBrolG6AtrkMh23qS+w3igW5qFsp9gkAJW4rrP1R1DJzb2EKgHFNXpFjcqpH+czr4forBNFQ1855/1OFY6dqzE92EGK0JUU5gjkX5hwNxSLjtE92ZDxbzlcHtg3AuynsjoeS5b9cij4Hqs+Pu6aqolp0GWmN6sal6xHC6ZzU9+4O/K2YNl34XHvRBYmmkYDyQCIrQnsiNoLL0Dtzr1kBYYOvM9Fpzq7LzgPV+QBzBdvax0IYcA=
  file: "datakit/build/outputs/apk/datakit*.*.*.apk"
  on:
    repo: MD2Korg/mCerebrum-DataKit
    tags: true
  skip_cleanup: true
notifications:
  slack:
    secure: drSaLEsi+xlUePocfcDTLO9S/5XSBsnR6h7OzPhU4xsO+mBjH3qb93Qe4Jwzz9IZQ0UFzDcmu7ObHOksd6fDgvnIcmznowuABs7QFSF5dodF3eXuF/NJc5J3SqptrOZhlPhGQJcan8siBpLw5z+UBal9ORQPJ8e0SN2bxvRH30GzOlaBOrS0w9hGmtoIY/c8ZIjxGn7BK+b7qL6pNqD4tTg3BImh4Q8Q0icjlT/Pe4kq9pJuYP+Ph4B6THE5PY6W5kmaPSZT2wk72tbNa+1f0lxkO106+Fi4X/qEf6BNQ/2ufUi8cGyjYhu8ZRfGEQVwmwtk0goZvPRyxzHx94tc0/utmW+ZvEEdXOTfs1cE84xGvsYOmoMaMacJC0DPSRTJ269LnmUlTYZoZPyEaqEJp0vFLnS7ZwYcYBzEQ/coS1zKOEWX5a29ijvCOxeFGWF9NcEvaGfpoP/RiLJXjguKfrQLQiek+xkzmubSRWpP9LFoqtXwVMxle/zi/99Ry02nvmEUSK3BbAM57LBnrT+0lYDC/ocxTpQ3Gvd52qFoZBzb8Fshu2+3UYCSCHROkOdHtBmBvRKE4LiTz8/6xtzeL1n+1RSrbN13tbk01gkNIHagSLWUildtFkvok2pJXawslE88ZhRzOOK8ViWFenbhca6sPfvBebXccTJKnzi4GQc=
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: sUejcym+QKM/zLLJCE0n1IQ2gTx2SbqYy2gSQ+KyZ9P9k6X9pHWaOm7+fTvDrqJGHaC4uKLdpGwbZCTaPKI3MsxLS0gDSRCRmhaGkdmsmroXg3FpMmLKPU0FnUp2dyOIJlg8Az4wrDUm5L3A3m7Uoa+CjfJLQQoIlekJE6NvN8QICI992wV+7q8ewXDb8tocArTK6tBAcjvhXXqDZiisE+4hk5WfbME7BB0Wo5iDcYVnEaWqPzOYHxOv756W3u7OAxC4Yy9pu3r1bQ5n9riVzRdKm9I2nfR30dBDWo/nBHWEtuolfH4XpQJ9d7bsXdtbpgUOLAREJN06XfpkXU+evq47Cp2CycE9l+tORb+Bo2mfJh93LqLmI9q/Rtt4hWb9/fh+cmpS/Dw+nET+dHylCRkA7b5X/may8ddyg6Wvi6fZqHxuaf8Tj9JtFJCWglsYbTGRtuiCIPC5ptSXZ8+dDfjXPtYdFvpmKq5q3vHmwb+WuxjZqGLhWbAJciyKGZD1snn6aKPy+x4+kyP035mo+dczMZPgRdUzwHmOBY/po2K5FDFQWYPJ/jeEJlDrWLKeOV3W73q92R6at7IfXqpFlGK+mVWuBm6pUK9NVyRggE+2+0mNE1pzrDUfEEoqGUmu3+JYRPD2upuyUlme8j6MTnEObG9deONx8AMYl8QeHek=
  - secure: uEcMhx/Dsx4kW3WKpdZF/l2h8Agmke7vcVYiTjZOQdWBBlb7zIZySoeDfXTRkth9G/23/RsZZlFTWluuWYvl+ykDpzFpPbIMtQ1sMWY9mvPvX4zibcHrpca6ugKu2Vxe2nH9cCNpEzYUhqfbdn5JggZCy4xIhFguJXrT12BJomH3SqUeL3NGZfQKZVFcWigCKJD5rsG28DyogNMW+WA9w7kcrosIO9U8EZj8Tv2ykTJcn+LWHuA9/yLVe4Xu+867nX8JXNESsPWk2LZ+ZX19H2f2+lNvcXUvq8z4CyB2rBWSvbJ+S6LnNiWSX3u6Ver1Al+x1kxwPWjKB5jJdF+cFHLN2N5vjHMArq5j39biYvOR0hczuRVkRe8cSwi/daJYBV6XzGClPNoW6BEQqITIr2xod1BoEoHs0s4X5MCf/kbpPQ10qCrfYmf36I4LRNcZqAzscLDfmoYEfRJZs8oCAzVxPn1uOIz+ozobWUtE+2gfnolHSTbOd/wHLcaUfOy9NRNeICx2TKvLWXrsPC4l+O5rQiDz/o4gAjGUeM/gqhHehZvyFiMXXoZnmKjK0anI7AHES0bSgTmtqvAENudt69VhVxSk4mDmJzxsDUgGJLStSUDH9qJo5NLxekR7BsqA6RgXLqzQbHGjYdqKGJUpEbhTv/ocKU1urJx/M7QbXmE=
  - secure: h7BIkb4JkXDLeus25/1c8hfUAiU6HHqunivWCy6r8csn/hwoDyJZNhrQP0wwM9kOLz54P9h6lcOAZ7LN4l8ho9NIjbq9CKBVvMr5iGgJqHFuisr7cJin1S4MjMu8BOCT1xYw7xcuqMl/CjTnjUeoRMaktz+cBniJ2+wemeXk2lHZbB8bdp99OakolE+pu3fJZjeMTxvcOW3cjK3gCqv9uTzS5nJyqbJasE755PDuvSan+Q7NO2zuYp9/ozzmD6FnEegFezZproS3fAV6q5bDCvn08T1X7XIY5VNoJCUFRItoIlQ7Xtixg1IpP+R3f+Ec4j3aC7ZaItlpWYFOSkAVDXUr5ODE4V8Ne9p8HEva5eQ0TT1LP7SBWSOxX0iay6OTZcDkt0ifCd8FD3RnDe4n4H4rZ44EnKpLLV8UNiI80lYQEacs6q1lumRR+o7HiuWWhSb12h9wG1ThRYlJMhaYfvi1F7n2JLBNmHyBVGH19l11oX5CHaAgIRxNdl2vUf3O42NU3Sj9asKlqQC8v6VOHeYQydJUN4CrVmrLUfEZyO87nRIGhQAxdmsOzTfQoQ5a+xLS/sSaxYG92sUMamHPxrxn0Y2sMSfSMF/X4+rhtDcJjX7xHQ3d51ALpREq+qEpnBZAGSWnRLLx5ZUfGazz8ulL2Or1OmzsKrGgF/stVNc=
  - secure: bhyQDu1v1lgKJtgvtBlGXNBa4EH3qbrRyq83qArAXOgPgUFijJ4heTRb8GlHWEC+Uw6Ex2Lkf2SvUq6P7bDFYN/4cvUHRGfqM9TGYc1Y7Z/Vd6ghZXSgiIVRwpKnHh3QqczmbeowRiV9h60WZ4K7uyeJuTEfYL/jsa4z0U+mE56JPwAfhVXEYnutoqb009miQ33/kPbo/bOe4WYfYymGvLXOdBO48bTjR1Jiw3raPYYhWD5AfZaZfcI2pDmvIt2by3+3uo7B8nj+vQrM+PrkqrGI8p2fbyu7TbZ5wOq53m4a/EIxtIsZQYPKgv8XQlbv4QTLM8hJ3uFy/mMJBkGCu1AD+71UetxqNOSVxkAeCdhpc/dRYl2AFbRMeCp/pAN2eNnlvLOBARG9QpROs3p5g5oBWu8zYGUTYkRL8AqBQJEcIlmFIlKyotoWFr+yMsgZ6tO/4yT+8EIfZjagOe3tGUa9BPHdM3uSdt0TJTPt6sJhus5FJZwcC6hRIyIhuQuD5W8XUsSa7FctrH14y8UxEsyAzYexA0aUfYYseeNZ+coGFUcOeg3ByVHWWjwMamvF/zEhpozsszBrVnaVeuXufg/eG/0Sd3olKcrfa6GcmlFAhfU6nCqUXfv1QOWXM6NZLsMc68DTRRtwfYIpnOjNBQzJ3YRNAATDspVPfTuA2Zk=


